
groups:
- name: alert.rules
  rules:
#  - alert: alerta
#    expr: 1
#    labels:
#      severity: "si"
#    annotations:
#      summary: "Alerta 1"
#      description: "Esta alarma es la 1"



  - alert: alert
    expr: my_metric{} == 0
    labels:
      severity: "si"
    annotations:
      summary: "Alerta 3"
      description: "Esta alarma es la 3"


  - alert: CPU
    expr: 1
    labels:
      severity: "Critical"
      category: memory
    annotations:
      summary: "La velocidad de la CPU es muy lenta"
      description: "La velocidad del cluster: {{ $labels.cluster }} Del job: {{ $labels.job }} es demasiado LENTA valor: {{ $value }} por más de 1 segundo"
      app_link: "https://monitoring.gc.syndeno.net/d/q8cAoXjdd/syndeno-monitoring-panel-alarmas-v2?orgId=1&from=1713943080584&to=1713946680584&viewPanel=61"
