route:
  group_by: ['alertname','client']
#  group_by: [...]
  group_wait: 1m #Tiempo de espera para agrupar para el mismo receptor
  group_interval: 1m #Agrupar alertas en un mismo mensaje, si son iguales
  repeat_interval: 2m
  receiver: admin
  routes:
    - match:
        severity: 'critical'
      receiver: admin
receivers:
- name: admin
  #group_by: ['client']
  email_configs:
  - to: 'ivan.carmona@syndeno.com'
    from: 'icc21010@gmail.com'
    headers:
      subject: '{{ if eq .Status "firing" }}Firing{{ else }}Resolved{{ end }}- {{ $foundValue := false }} {{ $value := "" }} {{ range .Alerts.Firing }} {{ if not $foundValue }} {{ $value = .Labels.cluster }} {{ $foundValue = true }} {{ end }} {{ end }} {{ if $foundValue }} {{ $value }} {{ else }} {{ end }} ·· {{ $foundValue := false }} {{ $value := "" }} {{ range .Alerts.Firing }} {{ if not $foundValue }} {{ $value = .Labels.alertname }} {{ $foundValue = true }} {{ end }} {{ end }} {{ if $foundValue }} {{ $value }} {{ else }} {{ end }}'
      pod: '{{ .CommonLabels.pod }}'
    html: '{{ template "alert.tmpl" . }}'
    smarthost: smtp.gmail.com:587                              #mx1.gc.syndeno.net:587
    auth_username: 'icc21010@gmail.com'
    auth_identity: 'icc21010@gmail.com'
    auth_password: 'zoelmpwtzjckwwrs '             #contraseña especial que se utiliza para comunicaciones ajbsralyyygsekau

templates:
  - '/etc/alertmanager/templates/alert.tmpl'
